spring.application.name=JevClassifier
spring.ai.openai.api-key=${OPEN_API_KEY}
# DATABASE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:~/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# JEV
jev.api.base-url=https://api.typesafe.ai
jev.api.key=${TYPESAFE_API_KEY}
jev.api.model=jev-latest
jev.api.timeout=10s